#!/bin/bash
## aws-polly
## version 0.0.1 - initial
##################################################
. ${SH2}/aliases/commands.sh
. ${SH2}/build.sh
. ${SH2}/cecho.sh
. ${SH2}/store.sh
. ${SH2}/install.sh
. $( dirname ${0} )/config.sh
substr() {
  local instr="${@}";
  local outstr="${instr:0:30}"
  {
    echo "${outstr}" \
    | sed 's/-*$//' - 
  }
}
slugify ()
{
    local instr="${@}";
    local outstr="${instr// /-}";
    local temp="${outstr,,}"
    echo $( substr ${temp} )
}
strip-comments() {
  sed -e 's/#.*//' -
}
voices() {
  cat << EOF
Joanna		# Woman neural
Kimberly	# Woman
Kendra		# Woman
Ivy		# Girl
Takumi		# Japanese guy
Mizuki		# Japanese girl
EOF
}
voice() { { local candidate_voice ; candidate_voice="${1}" ; }
  voices | grep -e "${candidate_voice}" | strip-comments
}
aws-polly-synthesize() { 
  local text
  local pattern
  local outfile
  local -i characters
  local -i lastrun
  local -i thisrun
  synthesize() {
    {
      aws polly synthesize-speech \
      --profile pollyuser \
      --output-format ${format:-mp3} \
      --voice-id ${voice:-Joanna} \
      --text "${text}" \
      ${outfile}
    }
  }
  init-pollyuser ()
  {
    echo "${init_pollyuser}" | xxd -ps -r | bash
  }
  bind-config-variables
  config
  {
    init-store
  } &>/dev/null
  read -p "Text: " text
  ## exit on case of empty text
  test "${text}" || {
    cecho yellow "Text empty"
    cecho green "Exiting ..."
    false
    return
  }
  pattern="[,.’?']"
  outfile="$( slugify ${text//${pattern}/} ).mp3"
  characters=$( store get characters )
  lastrun=$( store get lastrun )
  thisrun=$( date +%s )
  cecho yellow "text: \"${text}\""
  cecho yellow "outfile: ${outfile}"
  cecho yellow "characters: ${#text}"
  #cecho yellow "lastrun: ${lastrun}"
  #cecho yellow "thisrun: ${thisrun}"
  #cecho white "press enter key to continue"
  read 
  init-pollyuser
  synthesize $( voice ${voice} )
  store set history_$( store get run ) ${text}
  ## reset usage
  test $( date --date="@${lastrun}" "+%Y%m" ) = $( date --date="@${thisrun}" "+%Y%m" ) || {
    characters=0
  }
  store set characters $(( ${characters} + ${#text} ))
  store set lastrun ${thisrun}
  cecho yellow "MTD characters: $( store get characters ) ($(( 5000000 - $( store get characters ) )) characters remaining)"
  store persist
}
aws-polly-true() { 
  true
}
aws-polly-build() { 
  build=build
  build true
}
aws-polly-install() { 
  install polly \${HOME}/path-to-polly
}
aws-polly() { 
  commands
}
##################################################
aws-polly ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 06 Jan 2020 10:32:17 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
